### ISSUE TITLE
Don't assume ext4 or document ext4-requirement for /var/lib/docker

### ISSUE THREAD

**Issue by pnhofmann** [jeckel/volume-backup#2]
Using other filesystems than ext4 (like jfs, xfs, zfs, btrfs, ReiserFS, ext3, ...) for /var/lib/docker will break automatic volume scan - because that's the filesystem of volumes.

Please fix or document this limitation.

Don't really know, but I think something like
`mount | grep '^/[^/]' | grep -v /etc | grep -v 'on / ' | cut -d\  -f `
could work. "grep -v 'on / ' " is necesarry for btrfs. But there could be lots of other special cases.

**Comment by jeckel** [comment]
Thanks for reporting this, I'll try to fix it ASAP
